-- Create class_schedules table
CREATE TABLE IF NOT EXISTS public.class_schedules (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    department text not null,
    semester text not null,
    academic_year text not null,
    period text not null,
    courses jsonb not null
);

-- Enable RLS
ALTER TABLE public.class_schedules ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS "Enable read access for all users" ON public.class_schedules;
DROP POLICY IF EXISTS "Enable insert access for all users" ON public.class_schedules;
DROP POLICY IF EXISTS "Enable update access for all users" ON public.class_schedules;

-- Create policies (open for now as per other tables)
CREATE POLICY "Enable read access for all users" ON public.class_schedules FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.class_schedules FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON public.class_schedules FOR UPDATE USING (true);

-- Grant permissions
GRANT ALL ON TABLE public.class_schedules TO anon;
GRANT ALL ON TABLE public.class_schedules TO authenticated;
GRANT ALL ON TABLE public.class_schedules TO service_role;
