-- Comprehensive Fix for IonioPortal Tables and Permissions

-- 1. Create tables if they don't exist
CREATE TABLE IF NOT EXISTS public.weekly_menus (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    week_start text not null,
    week_end text not null,
    days jsonb not null
);

CREATE TABLE IF NOT EXISTS public.exam_schedules (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    department text not null,
    semester text not null,
    period text,
    exams jsonb not null
);

-- 2. Force Enable RLS
ALTER TABLE public.weekly_menus ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exam_schedules ENABLE ROW LEVEL SECURITY;

-- 3. Drop all existing policies to avoid conflicts
DROP POLICY IF EXISTS "Enable read access for all users" ON public.weekly_menus;
DROP POLICY IF EXISTS "Enable insert access for all users" ON public.weekly_menus;
DROP POLICY IF EXISTS "Enable update access for all users" ON public.weekly_menus;

DROP POLICY IF EXISTS "Enable read access for all users" ON public.exam_schedules;
DROP POLICY IF EXISTS "Enable insert access for all users" ON public.exam_schedules;
DROP POLICY IF EXISTS "Enable update access for all users" ON public.exam_schedules;

-- 4. Re-create open policies
-- For weekly_menus
CREATE POLICY "Enable read access for all users" ON public.weekly_menus FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.weekly_menus FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON public.weekly_menus FOR UPDATE USING (true);

-- For exam_schedules
CREATE POLICY "Enable read access for all users" ON public.exam_schedules FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.exam_schedules FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON public.exam_schedules FOR UPDATE USING (true);

-- 5. Grant permissions to standard roles (just in case)
GRANT ALL ON TABLE public.weekly_menus TO anon;
GRANT ALL ON TABLE public.weekly_menus TO authenticated;
GRANT ALL ON TABLE public.weekly_menus TO service_role;

GRANT ALL ON TABLE public.exam_schedules TO anon;
GRANT ALL ON TABLE public.exam_schedules TO authenticated;
GRANT ALL ON TABLE public.exam_schedules TO service_role;
